### ISSUE TITLE
tmux ctrl+b not working

### ISSUE THREAD

**Issue by kirkins** [deathbeam/dotfiles#1]
can't seem to do ctl+b then d to shut windows in tmux anymore

**Comment by deathbeam** [comment]
I remapped ctrl-b to screen-like ctrl-a (https://github.com/deathbeam/awesomedotrc/blob/master/dotfiles/tmux.conf#L7)

**Comment by kirkins** [comment]
So I want to delete everything before before line 36 to have default bindings but the UI changes and plugins?

**Comment by deathbeam** [comment]
Yes exactly. Also, if you really want to stick to tmux defaults, remove [tmux-sensible on this line](https://github.com/deathbeam/awesomedotrc/blob/master/dotfiles/tmux.conf#L106) too.

**Comment by kirkins** [comment]
Ok thanks! It looks like sensible mostly adds new commands so I might keep that. 

Just too use to ctl+d at this point.
