### ISSUE TITLE
Install issue?

### ISSUE THREAD

**Issue by kirkins** [deathbeam/dotfiles#2]
I installed this last night and I ended up commenting out line 7 of .vimrc 

```
Error detected while processing /home/philip/.vimrc:
line    7:
E488: Trailing characters: #source $VIMRUNTIME/defaults.vim
```

The line is:

`#source $VIMRUNTIME/defaults.vim`

Any idea what might have caused it? I'm running Ubuntu but I'm guessing it was tested mainly on arch?

**Comment by deathbeam** [comment]
I actually tested it on both Xubuntu and Arch (currently in process of switching from Xubuntu to Arch on my work computer). I think proper way of commenting out things in vimrs is to use `"` character and not `#`, so try to change that line to:

```
" source $VIMRUNTIME/defaults.vim
```

**Comment by kirkins** [comment]
Good catch I actually had, then I deleted the "

" # source 

But I'm wondering what I'm missing out on by commenting this out, if anything. What does VIMRUNTIME refer to?

**Comment by deathbeam** [comment]
`$VIMRUNTIME` is directory where all default Vim runtime files are stored. `defaults.vim` is default Vim configuration loaded when no `.vimrc` is present. You can see contents of it in [vim github repository](https://github.com/vim/vim/blob/master/runtime/defaults.vim).

**Comment by kirkins** [comment]
Wasn't sure where else to comment but .... DAMN SON CI INTEGRATION FOR YOUR DOT FILES

BTFO!!!!!
