### ISSUE TITLE
Something broke

### ISSUE THREAD

**Issue by kirkins** [deathbeam/dotfiles#4]
I updated and something broke along the way.

```
base16_tomorrow-night: command not found
bash: /lib/bash/fasd/fasd: No such file or directory
No command 'fasd' found, did you mean:
 Command 'nasd' from package 'nas' (universe)
 Command 'fasm' from package 'fasm' (universe)
 Command 'fastd' from package 'fastd' (universe)
 Command 'famd' from package 'fam' (universe)
 Command 'faad' from package 'faad' (universe)
 Command 'afsd' from package 'openafs-client' (universe)
fasd: command not found
```
Any advice?

**Comment by deathbeam** [comment]
Yep, I moved some enviroment variables declaration to ~/.bash_profile, along with $ARC variable, what based on error your .bashrc cannot find. So try manually sourcing ~/.bash_profile, then it should work.

**Comment by kirkins** [comment]
hmm when I do that it returns the same error as above.

Luckily I do have a bash still open from before I made the change which is working perfectly fine to fix anything. Any new terminals seem to have the path issue.

**Comment by deathbeam** [comment]
Can you show me output of `echo $0` and `cat ~/.adrc`?

**Comment by kirkins** [comment]
I get back 'bash' and 'export ARC=/home/philip/tmp/awesomedotrc'

**Comment by deathbeam** [comment]
Oh, so you are running non-login shell then, that is loading only ~/.bashrc and not ~/.bash_profile. And ~/.bash_profile can or cannot be loaded when you login to your environment, so you probably need to logout and log back in. ~/.profile will be loaded for sure when logging in, so going to make small update that will move stuff to ~/.profile

EDIT: Or I can just move it back to ~/.bashrc

**Comment by kirkins** [comment]
Ok I applied the update and here is where I am now. I posted a picture because the color of my pointer changed but that's probably just your new theme kicking in.

![screenshot from 2016-11-02 20-23-48](https://cloud.githubusercontent.com/assets/9503662/19952286/7cbbf7ca-a13a-11e6-8df1-4cd728aa435c.png)

This fixes it but every-time I close the terminal and re-open I have to do it all over again.

**Comment by kirkins** [comment]
ok nvm the color thing it did change but it changed both instances at once lol

**Comment by deathbeam** [comment]
I'm confused, so it is working or not? 😄

**Comment by kirkins** [comment]
It's not working. I have to source ~/.bash_profile every-time I open a new terminal. I restarted too.

**Comment by deathbeam** [comment]
Hmm, that is weird, because I moved everything back to ~/.bashrc. Maybe [this line](https://github.com/deathbeam/awesomedotrc/blob/master/dotfiles/bashrc#L10) is causing it. Can you try to remove it, if it works for you? But if it is causing it, it would be really weird, because that will mean that you are not even running interactive shell.

**Comment by kirkins** [comment]
Ok sorry about that. I'm not sure what went wrong but when I looked in /dotfiles/bashrc my copy was completely different.

I deleted everything and re-cloned your latest build and it works perfectly.
